USE [MOVIESDB]
GO

/****** Object:  Table [dbo].[Genres]    Script Date: 09/10/22 12:19:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Genres](
	[GenreID] [int] IDENTITY(1,3) NOT NULL,
	[GenreName] [varchar](50) NULL,
 CONSTRAINT [PK_Genres1] PRIMARY KEY CLUSTERED 
(
	[GenreID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


